CREATE TABLE games(
  id           INTEGER  NOT NULL PRIMARY KEY,
  title        VARCHAR(255) NOT NULL,
  image        VARCHAR(511) NOT NULL,
  genre        VARCHAR(255) NOT NULL,
  platforms0   VARCHAR(255) NOT NULL,
  platforms1   VARCHAR(255),
  platforms2   VARCHAR(255),
  release_date DATE  NOT NULL,
  developer    VARCHAR(255) NOT NULL,
  publisher    VARCHAR(255) NOT NULL,
  rating       VARCHAR(255) NOT NULL,
  description  LONGTEXT NOT NULL,
  price        NUMERIC(5,2) NOT NULL
);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (1,'The Witcher 3: Wild Hunt','https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png','Action RPG','PlayStation 4','Xbox One','PC','2015-05-19','CD Projekt Red','CD Projekt','Mature','An open-world action RPG set in a dark fantasy universe, featuring rich storytelling, dynamic combat, and vast exploration.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (2,'The Legend of Zelda: Breath of the Wild','https://static.posters.cz/image/750/affiches-et-posters/the-legend-of-zelda-breath-of-the-wild-sunset-i40519.jpg','Action-Adventure','Nintendo Switch','Wii U',NULL,'2017-03-03','Nintendo EPD','Nintendo','Everyone 10+','An expansive open-world adventure game set in the kingdom of Hyrule, offering freedom of exploration, inventive puzzles, and immersive gameplay.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (3,'Red Dead Redemption 2','https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png','Action-Adventure','PlayStation 4','Xbox One','PC','2018-10-26','Rockstar Studios','Rockstar Games','Mature','A sprawling Western epic set in the dying days of the American Wild West, offering a deeply immersive open-world experience with stunning visuals and engaging narrative.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (4,'Super Mario Odyssey','https://eq9q4mywfv4.exactdn.com/wp-content/uploads/2022/07/Super-Mario-Odyssey-Featured-Ecran-Partage.jpg?strip=all&lossy=1&ssl=1','Platformer','Nintendo Switch',NULL,NULL,'2017-10-27','Nintendo EPD','Nintendo','Everyone 10+','A vibrant 3D platformer that takes players on a globe-trotting adventure with Mario, featuring inventive level design, charming characters, and joyful gameplay.',49.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (5,'Horizon Zero Dawn','https://cdn1.epicgames.com/3328b08ac1c14540aa265a1a85c07839/offer/hzd_wide-2560x1440-bd312be05c49cf339097777c493cb899.jpg','Action RPG','PlayStation 4','PC',NULL,'2017-02-28','Guerrilla Games','Sony Interactive Entertainment','Teen','A post-apocalyptic action RPG set in a lush open world overrun by robotic creatures, featuring thrilling combat and a captivating story.',49.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (6,'God of War','https://cdn1.epicgames.com/offer/3ddd6a590da64e3686042d108968a6b2/EGS_GodofWar_SantaMonicaStudio_S2_1200x1600-fbdf3cbc2980749091d52751ffabb7b7_1200x1600-fbdf3cbc2980749091d52751ffabb7b7','Action-Adventure','PlayStation 4',NULL,NULL,'2018-04-20','Santa Monica Studio','Sony Interactive Entertainment','Mature','A reimagining of the iconic series, following Kratos and his son Atreus on a deeply personal journey through Norse mythology, featuring visceral combat and stunning visuals.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (7,'Grand Theft Auto V','https://image.api.playstation.com/vulcan/ap/rnd/202203/0911/VIB0SeEj9vT6DTv7P4thJLZi.jpg','Action-Adventure','PlayStation 4','Xbox One','PC','2013-09-17','Rockstar North','Rockstar Games','Mature','An open-world crime epic set in the fictional state of San Andreas, offering a vast playground for mayhem and exploration, both solo and in multiplayer.',29.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (8,'Dark Souls III','https://image.api.playstation.com/cdn/EP0700/CUSA03365_00/OFMeAw2KhrdaEZAjW1f3tCIXbogkLpTC.png','Action RPG','PlayStation 4','Xbox One','PC','2016-04-12','FromSoftware','Bandai Namco Entertainment','Mature','A challenging action RPG set in a dark fantasy world, known for its punishing difficulty, intricate level design, and deep lore.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (9,'The Elder Scrolls V: Skyrim','https://assets-prd.ignimgs.com/2021/08/19/elder-scrolls-skyrim-button-2017-1629409446732.jpg','Action RPG','Multiplatform',NULL,NULL,'2011-11-11','Bethesda Game Studios','Bethesda Softworks','Mature','An epic open-world RPG set in the fantasy realm of Tamriel, offering boundless exploration, rich storytelling, and countless quests.',39.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (10,'Overwatch 2','https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_Overwatch2_Season6_image1600w.png','Hero Shooter','PlayStation 4','Xbox One','PC','2016-05-24','Blizzard Entertainment','Blizzard Entertainment','Teen','A team-based multiplayer shooter featuring a diverse cast of heroes, each with unique abilities, offering fast-paced action and strategic gameplay.',39.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (11,'Cyberpunk 2077','https://www.cyberpunk.net/build/images/pre-order/buy-b/keyart-ue-fr@2x-cd66fd0d.jpg','Action RPG','PlayStation 4','Xbox One','PC','2020-12-10','CD Projekt Red','CD Projekt','Mature','A futuristic open-world RPG set in the dystopian metropolis of Night City, offering deep customization, branching storylines, and immersive world-building.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (12,'Final Fantasy VII Remake','https://image.api.playstation.com/vulcan/ap/rnd/202308/3005/537b5208a8ee42935286a44b3b981da86d976bf54899bf98.jpg','Action RPG','PlayStation 4',NULL,NULL,'2020-04-10','Square Enix','Square Enix','Teen','A reimagining of the classic RPG, featuring stunning visuals, dynamic combat, and expanded storytelling in the city of Midgar.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (13,'Super Smash Bros. Ultimate','https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/software/switch/70010000012332/ac4d1fc9824876ce756406f0525d50c57ded4b2a666f6dfe40a6ac5c3563fad9','Fighting','Nintendo Switch',NULL,NULL,'2018-12-07','Bandai Namco Studios / Sora Ltd.','Nintendo','Everyone 10+','A crossover fighting game featuring an expansive roster of iconic characters from various video game franchises, offering frantic multiplayer battles and solo challenges.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (14,'Bloodborne','https://image.api.playstation.com/vulcan/img/rnd/202010/2614/NVmnBXze9ElHzU6SmykrJLIV.png','Action RPG','PlayStation 4',NULL,NULL,'2015-03-24','FromSoftware','Sony Interactive Entertainment','Mature','A challenging action RPG set in a gothic horror world, known for its fast-paced combat, intricate level design, and haunting atmosphere.',19.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (15,'Fortnite','https://cdn1.epicgames.com/offer/fn/Blade_2560x1440_2560x1440-95718a8046a942675a0bc4d27560e2bb','Battle Royale','Multiplatform',NULL,NULL,'2017-07-25','Epic Games','Epic Games','Teen','A free-to-play battle royale game that pits players against each other in a vibrant, ever-changing island environment, offering building mechanics and constant updates.',0);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (16,'Among Us','https://cdn1.epicgames.com/salesEvent/salesEvent/amoguslandscape_2560x1440-3fac17e8bb45d81ec9b2c24655758075','Social Deduction','Multiplatform',NULL,NULL,'2018-06-15','InnerSloth','InnerSloth','Everyone 10+','A multiplayer social deduction game where players work together to complete tasks on a spaceship while attempting to identify the impostors among them.',4.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (17,'Pokémon Sword and Shield','https://www.nintendo.com/sg/switch/sword_shield/img/hero_sp.jpg','RPG','Nintendo Switch',NULL,NULL,'2019-11-15','Game Freak','Nintendo / The Pokémon Company','Everyone','An RPG adventure set in the Galar region, where players embark on a journey to become the Champion, capturing and battling Pokémon along the way.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (18,'Call of Duty: Warzone','https://www.laptopspirit.fr/wp-content/uploads/new/2022/02/Call-of-Duty-Warzone-1536x864-1.jpg','Battle Royale','PlayStation 4','Xbox One','PC','2020-03-10','Infinity Ward / Raven Software','Activision','Mature','A free-to-play battle royale game set in the Call of Duty universe, featuring fast-paced combat, strategic gameplay, and cross-platform support.',0);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (19,'The Last of Us Part II','https://image.api.playstation.com/vulcan/ap/rnd/202312/0117/da083fa5e19458dd750aa8a6ea30ba10bac6f87074693df5.jpg','Action-Adventure','PlayStation 4',NULL,NULL,'2020-06-19','Naughty Dog','Sony Interactive Entertainment','Mature','A gripping action-adventure game set in a post-apocalyptic world, featuring intense combat, emotional storytelling, and stunning visuals.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (20,'Doom Eternal','https://image.api.playstation.com/vulcan/ap/rnd/202010/0114/b4Q1XWYaTdJLUvRuALuqr0wP.png','First-Person Shooter','PlayStation 4','Xbox One','PC','2020-03-20','id Software','Bethesda Softworks','Mature','A relentless first-person shooter that puts players in the role of the Doom Slayer, battling hordes of demons across dimensions, featuring fast-paced action and visceral combat.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (21,'Assassin''s Creed Valhalla','https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png','Action RPG','PlayStation 4','Xbox One','PC','2020-11-10','Ubisoft Montreal','Ubisoft','Mature','An epic action RPG set in the Viking age, allowing players to lead their clan to victory in England, featuring exploration, combat, and political intrigue.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (22,'Hades','https://image.jeuxvideo.com/medias/161367/1613665411-7537-jaquette-avant.png','Action RPG','Nintendo Switch','PC',NULL,'2020-09-17','Supergiant Games','Supergiant Games','Teen','A rogue-like action RPG where players fight their way out of the underworld as the immortal prince of the Greek gods, featuring fast-paced combat and rich storytelling.',24.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (23,'Ghost of Tsushima','https://image.api.playstation.com/vulcan/ap/rnd/202106/2322/ZSrFeb6XkqKiq2PZKWg20yfe.jpg','Action-Adventure','PlayStation 4',NULL,NULL,'2020-07-17','Sucker Punch Productions','Sony Interactive Entertainment','Mature','An open-world action-adventure game set in feudal Japan, where players take on the role of a samurai fighting to liberate the island of Tsushima from Mongol invaders.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (24,'Valorant','https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2020/6/5/ctsejxmdtw9inp8zqqqd/red-bull-campus-clutch-valorant-agents','Hero Shooter','PC',NULL,NULL,'2020-06-02','Riot Games','Riot Games','Teen','A free-to-play tactical shooter where players compete in 5v5 matches, combining precise gunplay with unique agent abilities in a round-based format.',0);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (25,'The Outer Worlds','https://image.api.playstation.com/vulcan/img/cfn/11307DWVuREjDv3JnXusQxTjHIJHzhxx2_CUkUzQhzwYe5KUktTVe2_rFsnYYa1hMNlqHrWemXr0Nut__AF2KWPJp84uBZvf.png','Action RPG','PlayStation 4','Xbox One','PC','2019-10-25','Obsidian Entertainment','Private Division','Mature','A satirical single-player RPG set in a retro-futuristic universe, featuring branching narratives, player choice, and dark humor.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (26,'Crash Bandicoot 4: It''s About Time','https://image.api.playstation.com/vulcan/img/rnd/202111/1918/psoOkDbYuMdr1RsJo6TpU6bg.png','Platformer','PlayStation 4','Xbox One',NULL,'2020-10-02','Toys for Bob','Activision','Everyone 10+','A colorful platformer featuring the iconic marsupial, Crash Bandicoot, on a new adventure through time and space, with challenging levels and nostalgic gameplay.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (27,'Marvel''s Spider-Man: Miles Morales','https://image.api.playstation.com/vulcan/ap/rnd/202008/1020/PRfYtTZQsuj3ALrBXGL8MjAH.jpg','Action-Adventure','PlayStation 4','PlayStation 5',NULL,'2020-11-12','Insomniac Games','Sony Interactive Entertainment','Teen','A thrilling action-adventure game where players step into the shoes of Miles Morales as he becomes the new Spider-Man, swinging through the streets of New York City.',49.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (28,'Destiny 2','https://cdn1.epicgames.com/offer/428115def4ca4deea9d69c99c5a5a99e/EN_Bungie_Legacy_Collection_2023_S3_2560x1440_2560x1440-c12dafc5484d838c29532a5e8c87fd74','MMO Shooter','Multiplatform',NULL,NULL,'2017-09-06','Bungie','Bungie','Teen','A sci-fi MMO shooter set in a rich universe filled with action and adventure, featuring cooperative and competitive gameplay, as well as a deep progression system.',0);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (29,'Apex Legends','https://image.api.playstation.com/vulcan/ap/rnd/202401/1810/63e55900b867e1d9e50bf139f92fe1fe94e9a048503990d3.png','Battle Royale','Multiplatform',NULL,NULL,'2019-02-04','Respawn Entertainment','Electronic Arts','Teen','A free-to-play battle royale game set in the Titanfall universe, featuring diverse characters with unique abilities and fast-paced combat.',0);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (30,'DOOM (2016)','https://image.api.playstation.com/vulcan/ap/rnd/202009/2814/GGyEnCkIXoyiVlN9sRHkzUPo.png','First-Person Shooter','Multiplatform',NULL,NULL,'2016-05-13','id Software','Bethesda Softworks','Mature','A high-octane first-person shooter where players battle hordes of demons from Hell, featuring fast-paced action, brutal weapons, and relentless combat.',19.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (31,'Sekiro: Shadows Die Twice','https://cdn.cloudflare.steamstatic.com/steam/apps/814380/capsule_616x353.jpg?t=1678991267','Action-Adventure','PlayStation 4','Xbox One','PC','2019-03-22','FromSoftware','Activision','Mature','A challenging action-adventure game set in feudal Japan, where players assume the role of a shinobi seeking revenge, featuring intense swordplay and stealth mechanics.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (32,'The Legend of Zelda: Link''s Awakening','https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheLegendOfZeldaLinksAwakening_image1600w.jpg','Action-Adventure','Nintendo Switch',NULL,NULL,'2019-09-20','Nintendo EPD','Nintendo','Everyone','A whimsical action-adventure game set on the mysterious Koholint Island, where players guide Link on a quest to awaken the Wind Fish, encountering charming characters and challenging dungeons.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (33,'Sea of Thieves','https://image.jeuxvideo.com/medias/152240/1522396063-3523-jaquette-avant.jpg','Action-Adventure','Xbox One','PC',NULL,'2018-03-20','Rare','Xbox Game Studios','Teen','A cooperative multiplayer game where players embark on pirate adventures, exploring a vast open world, battling rival crews, and seeking treasure in a shared online experience.',39.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (34,'Halo Infinite','https://pic.clubic.com/v1/images/1811528/raw','First-Person Shooter','Xbox Series X/S','Xbox One','PC','2021-12-08','343 Industries','Xbox Game Studios','Teen','An upcoming installment in the iconic Halo series, featuring Master Chief''s return in an epic campaign and intense multiplayer battles across a vast sci-fi universe.',59.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (35,'Monster Hunter: World','https://gaming-cdn.com/images/products/3220/orig/monster-hunter-world-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-jeu-microsoft-store-europe-cover.jpg?v=1703157851','Action RPG','PlayStation 4','Xbox One','PC','2018-01-26','Capcom','Capcom','Teen','An action RPG where players hunt down gigantic monsters in a lush ecosystem, collecting resources, crafting gear, and mastering various weapon types.',29.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (36,'Mortal Kombat 11','https://image.api.playstation.com/vulcan/ap/rnd/202010/0822/4WzxHtmjXV1dQpWqj1B6UAMk.jpg','Fighting','Multiplatform',NULL,NULL,'2019-04-23','NetherRealm Studios','Warner Bros. Interactive Entertainment','Mature','The latest installment in the iconic fighting game franchise, featuring brutal combat, cinematic storytelling, and a diverse roster of fighters.',49.99);
INSERT INTO games(id,title,image,genre,platforms0,platforms1,platforms2,release_date,developer,publisher,rating,description,price) VALUES (37,'Fallout 76','https://images.ctfassets.net/rporu91m20dc/2a3wESrWweWSZkTbNrXo2/2c29f6de40a685e412886db7edfeb096/FO76-Wastelanders-SteelDawn_Screens_01-SteelDawn-THUMB1.jpg','Action RPG','PlayStation 4','Xbox One','PC','2018-11-14','Bethesda Game Studios','Bethesda Softworks','Mature','An online multiplayer RPG set in the Fallout universe, where players explore a post-apocalyptic world, build settlements, and engage in quests and events.',39.99);